
export const API_CATEGORY_URL = 'http://localhost:8080/api/convenient';
export const API_HOUSE_URL = 'http://localhost:8080/api/house';
export const API_HOUSE_DETAIL_URL = 'http://localhost:8080/api/house/detail/';
export const API_HOUSE_COMFORTABLE_DETAIL = 'http://localhost:8080/api/house/detail/comfortable/';
export const API_HOUSE_REVIEW = 'http://localhost:8080/api/house/detail/review/';
export const API_HOUSE_REVIEWS = 'http://localhost:8080/api/house/detail/reviews/';
export const API_HOUSE_DETAIL_PRICE = 'http://localhost:8080/api/house/detail/price/';
export const API_CREATE_BOOK_HOUSE = 'http://localhost:8080/api/guest/reservation/create';
export const API_RESERVATION_HOUSE = 'http://localhost:8080/api/reservation';
export const API_GET_HOUSES_BY_COMFORTABLE_ID = 'http://localhost:8080/api/comfortable/';
export const API_GET_LIST_FILTER = 'http://localhost:8080/api/comfortable/list-filter';
export const API_GET_HOUSE_BY_CITY = 'http://localhost:8080/api/house/search/';
export const API_USER_AUTH_URL = 'http://localhost:8080/api/auth'
export const API_USER_URL = 'http://localhost:8080/api/user'
export const API_GET_USER_INFO = 'http://localhost:8080/api/guest/user/get-info';
export const API_UPDATE_USER_INFO ='http://localhost:8080/api/guest/user/update-info';
export const API_BLOCKING_DATE_BY_HOUSE_ID = 'http://localhost:8080/api/multiCalendars/client/getBlockingDate/';
export const API_BLOCK_REVERSATION_BY_HOUSE_ID = 'http://localhost:8080/api/reservation/block/';
export const API_GET_WISH_LISTS_BY_USER = 'http://localhost:8080/api/house/client/wishlists';
export const API_DELETE_WISH_LISTS_BY_ID = 'http://localhost:8080/api/house/client/delete-wishlist/';
export const API_CREATE_NEW_LIST = 'http://localhost:8080/api/house/client/create-wishlist'
export const API_GET_FAVORITE_HOUSE_BY_USER = 'http://localhost:8080/api/house/client/favorite-houses'
export const API_REMOVE_HOUSE_FAVORITE = 'http://localhost:8080/api/house/client/remove-house-favorite/';
export const API_ADD_FAVORITE_HOUSE ='http://localhost:8080/api/house/client/add-wishlist/' ;
export const API_DETAILS_WISH_LIST ='http://localhost:8080/api/house/client/wishlists/';
export const API_GET_HISTORY_RESERVATION = 'http://localhost:8080/api/reservation/history';
export const API_CANCEL_RESERVATION = 'http://localhost:8080/api/reservation/cancel/';