
export const API_CATEGORY_URL = 'https://quarter-rois.cghue.com/api/convenient';
export const API_HOUSE_URL = 'https://quarter-rois.cghue.com/api/house';
export const API_HOUSE_DETAIL_URL = 'https://quarter-rois.cghue.com/api/house/detail/';
export const API_HOUSE_COMFORTABLE_DETAIL = 'https://quarter-rois.cghue.com/api/house/detail/comfortable/';
export const API_HOUSE_REVIEW = 'https://quarter-rois.cghue.com/api/house/detail/review/';
export const API_HOUSE_REVIEWS = 'https://quarter-rois.cghue.com/api/house/detail/reviews/';
export const API_HOUSE_DETAIL_PRICE = 'https://quarter-rois.cghue.com/api/house/detail/price/';
export const API_CREATE_BOOK_HOUSE = 'https://quarter-rois.cghue.com/api/guest/reservation/create';
export const API_RESERVATION_HOUSE = 'https://quarter-rois.cghue.com/api/reservation';
export const API_GET_HOUSES_BY_COMFORTABLE_ID = 'https://quarter-rois.cghue.com/api/comfortable/';
export const API_GET_LIST_FILTER = 'https://quarter-rois.cghue.com/api/comfortable/list-filter';
export const API_GET_HOUSE_BY_CITY = 'https://quarter-rois.cghue.com/api/house/search/';
export const API_USER_AUTH_URL = 'https://quarter-rois.cghue.com/api/auth'
export const API_USER_URL = 'https://quarter-rois.cghue.com/api/user'
export const API_GET_USER_INFO = 'https://quarter-rois.cghue.com/api/guest/user/get-info';
export const API_UPDATE_USER_INFO ='https://quarter-rois.cghue.com/api/guest/user/update-info';
export const API_BLOCKING_DATE_BY_HOUSE_ID = 'https://quarter-rois.cghue.com/api/multiCalendars/client/getBlockingDate/';
export const API_BLOCK_REVERSATION_BY_HOUSE_ID = 'https://quarter-rois.cghue.com/api/reservation/block/';
export const API_GET_WISH_LISTS_BY_USER = 'https://quarter-rois.cghue.com/api/house/client/wishlists';
export const API_DELETE_WISH_LISTS_BY_ID = 'https://quarter-rois.cghue.com/api/house/client/delete-wishlist/';
export const API_CREATE_NEW_LIST = 'https://quarter-rois.cghue.com/api/house/client/create-wishlist'
export const API_GET_FAVORITE_HOUSE_BY_USER = 'https://quarter-rois.cghue.com/api/house/client/favorite-houses'
export const API_REMOVE_HOUSE_FAVORITE = 'https://quarter-rois.cghue.com/api/house/client/remove-house-favorite/';
export const API_ADD_FAVORITE_HOUSE ='https://quarter-rois.cghue.com/api/house/client/add-wishlist/' ;
export const API_DETAILS_WISH_LIST ='https://quarter-rois.cghue.com/api/house/client/wishlists/';
export const API_GET_HISTORY_RESERVATION = 'https://quarter-rois.cghue.com/api/reservation/history';
export const API_CANCEL_RESERVATION = 'https://quarter-rois.cghue.com/api/reservation/cancel/';
export const API_GET_ALL_INFORMATION_USER ='https://quarter-rois.cghue.com/api/client/users/detail/';
export const API_GET_REVIEWS_FROM_GUEST = 'https://quarter-rois.cghue.com/api/client/users/detail/review/1/'
export const API_GET_REVIEWS_FROM_HOST = 'https://quarter-rois.cghue.com/api/client/users/detail/review/2/'
export const API_ADMIN = 'https://quarter-rois.cghue.com/api/admin/'
export const API_HOST = 'https://quarter-rois.cghue.com/api/host/'